<style>
.jp-RenderedHTMLCommon table,
.rendered_html table {
  margin-left: 0 !important;
  margin-right: auto !important;
}
.jp-RenderedHTMLCommon th,
.jp-RenderedHTMLCommon td,
.rendered_html th,
.rendered_html td {
  text-align: left !important;
}
</style>

# 02 - Python, NumPy, and Pandas Foundations

<div style="background:#F7FAFC; border:1px solid #D9E2EC; border-left:6px solid #2F80ED; padding:14px; border-radius:6px;">
<img src="../../../assets/icons/goal.svg" width="22" style="vertical-align:middle; margin-right:6px;"><b>Notebook Header</b><br>
<b>Day:</b> Day 1 - EDA and preprocessing foundations<br>
<b>Difficulty:</b> Beginner<br>
<b>Estimated time:</b> 45-60 minutes<br>
<b>Prerequisites:</b> Notebook 01 completed<br>
<b>Output:</b> You will create and manipulate simple Python, NumPy, and Pandas objects.<br>
<b>Next notebook:</b> Data inspection and cleaning
</div>

<details>
<summary><b>Instructor talk track</b></summary>

This notebook is about comfort. Learners should not memorize every function. They should understand that Python stores values, NumPy works well with numbers, and Pandas works well with tables.

</details>

## <img src="../../../assets/icons/map.svg" width="22" style="vertical-align:middle; margin-right:6px;"> Learning Map

By the end of this notebook, you should be able to:

- Create Python variables
- Use lists to store multiple values
- Use dictionaries to store labeled values
- Create NumPy arrays
- Run simple NumPy calculations
- Create Pandas Series and DataFrames
- Select, filter, sort, and summarize table data

## <img src="../../../assets/icons/loop.svg" width="22" style="vertical-align:middle; margin-right:6px;"> Signature Learning Loop

```text
QUESTION -> DATA -> CODE -> EVIDENCE -> DECISION
```

## <img src="../../../assets/icons/concept.svg" width="22" style="vertical-align:middle; margin-right:6px;"> Concept 1: Python Variables

<div style="background:#EAF3FF; border-left:6px solid #2F80ED; padding:14px; border-radius:6px;">
<img src="../../../assets/icons/concept.svg" width="22" style="vertical-align:middle; margin-right:6px;"><b>Concept</b><br>
A variable is a name that stores a value.
</div>

### Why this matters

- Data work needs values stored with clear names.
- Good variable names make code easier to read.
- Variables can store text, numbers, and other objects.

<div style="background:#E9F8EF; border-left:6px solid #27AE60; padding:14px; border-radius:6px;">
<img src="../../../assets/icons/code.svg" width="22" style="vertical-align:middle; margin-right:6px;"><b>Code Lab</b><br>
Create a few variables for a customer purchase example.
</div>

<div style="background:#FFF8E1; border-left:6px solid #F2C94C; padding:14px; border-radius:6px;">
<img src="../../../assets/icons/read-output.svg" width="22" style="vertical-align:middle; margin-right:6px;"><b>Read the Output</b><br>
Check how each variable name makes the stored value understandable.
</div>

In [1]:
customer_name = "Asha"
city = "Mumbai"
monthly_spend = 1200
visits_per_month = 4

print("Customer:", customer_name)
print("City:", city)
print("Monthly spend:", monthly_spend)
print("Visits per month:", visits_per_month)

Customer: Asha
City: Mumbai
Monthly spend: 1200
Visits per month: 4

## <img src="../../../assets/icons/concept.svg" width="22" style="vertical-align:middle; margin-right:6px;"> Concept 2: Python Lists

<div style="background:#EAF3FF; border-left:6px solid #2F80ED; padding:14px; border-radius:6px;">
<img src="../../../assets/icons/concept.svg" width="22" style="vertical-align:middle; margin-right:6px;"><b>Concept</b><br>
A list stores multiple values in order.
</div>

### List basics

- Lists use square brackets: `[]`
- The first item is at position `0`
- Lists are useful for storing small collections

<div style="background:#E9F8EF; border-left:6px solid #27AE60; padding:14px; border-radius:6px;">
<img src="../../../assets/icons/code.svg" width="22" style="vertical-align:middle; margin-right:6px;"><b>Code Lab</b><br>
Create a list of monthly purchase amounts.
</div>

In [2]:
purchase_amounts = [1200, 850, 1450, 700, 2200]

print("All purchases:", purchase_amounts)
print("First purchase:", purchase_amounts[0])
print("Number of purchases:", len(purchase_amounts))
print("Total purchase amount:", sum(purchase_amounts))

All purchases: [1200, 850, 1450, 700, 2200]
First purchase: 1200
Number of purchases: 5
Total purchase amount: 6400

## <img src="../../../assets/icons/concept.svg" width="22" style="vertical-align:middle; margin-right:6px;"> Concept 3: Python Dictionaries

<div style="background:#EAF3FF; border-left:6px solid #2F80ED; padding:14px; border-radius:6px;">
<img src="../../../assets/icons/concept.svg" width="22" style="vertical-align:middle; margin-right:6px;"><b>Concept</b><br>
A dictionary stores key-value pairs.
</div>

### Why dictionaries matter

- They attach labels to values.
- One dictionary can represent one record.
- A row in a table is similar to a labeled record.

<div style="background:#E9F8EF; border-left:6px solid #27AE60; padding:14px; border-radius:6px;">
<img src="../../../assets/icons/code.svg" width="22" style="vertical-align:middle; margin-right:6px;"><b>Code Lab</b><br>
Create one customer record as a dictionary.
</div>

In [3]:
customer = {
    "customer_id": 101,
    "name": "Asha",
    "city": "Mumbai",
    "monthly_spend": 1200,
    "visits_per_month": 4,
}

print(customer)
print("Customer city:", customer["city"])
print("Monthly spend:", customer["monthly_spend"])

{'customer_id': 101, 'name': 'Asha', 'city': 'Mumbai', 'monthly_spend': 1200, 'visits_per_month': 4}
Customer city: Mumbai
Monthly spend: 1200

## <img src="../../../assets/icons/practice.svg" width="22" style="vertical-align:middle; margin-right:6px;"> Checkpoint 1: Python Objects

Answer these before continuing:

1. What is the purpose of a variable?
2. When would you use a list?
3. Why is a dictionary easier to understand than an unlabeled list?

<div style="background:#FFF8E1; border-left:6px solid #F2C94C; padding:14px; border-radius:6px;">
<img src="../../../assets/icons/read-output.svg" width="22" style="vertical-align:middle; margin-right:6px;"><b>Expected thinking</b><br>
Variables store one object, lists store ordered values, and dictionaries store labeled values.
</div>

## <img src="../../../assets/icons/concept.svg" width="22" style="vertical-align:middle; margin-right:6px;"> Concept 4: NumPy Arrays

<div style="background:#EAF3FF; border-left:6px solid #2F80ED; padding:14px; border-radius:6px;">
<img src="../../../assets/icons/concept.svg" width="22" style="vertical-align:middle; margin-right:6px;"><b>Concept</b><br>
A NumPy array stores numeric values and supports fast calculations.
</div>

### Why NumPy is useful

- It is efficient for numerical data.
- It supports element-wise operations.
- It is used internally by many data science libraries.

<div style="background:#E9F8EF; border-left:6px solid #27AE60; padding:14px; border-radius:6px;">
<img src="../../../assets/icons/code.svg" width="22" style="vertical-align:middle; margin-right:6px;"><b>Code Lab</b><br>
Convert a Python list into a NumPy array.
</div>

In [4]:
import numpy as np

spend_array = np.array([1200, 850, 1450, 700, 2200])

print("Array:", spend_array)
print("Type:", type(spend_array))
print("Average spend:", spend_array.mean())
print("Highest spend:", spend_array.max())

Array: [1200  850 1450  700 2200]
Type: <class 'numpy.ndarray'>
Average spend: 1280.0
Highest spend: 2200

## <img src="../../../assets/icons/concept.svg" width="22" style="vertical-align:middle; margin-right:6px;"> Concept 5: NumPy Element-Wise Operations

<div style="background:#EAF3FF; border-left:6px solid #2F80ED; padding:14px; border-radius:6px;">
<img src="../../../assets/icons/concept.svg" width="22" style="vertical-align:middle; margin-right:6px;"><b>Concept</b><br>
Element-wise operation means the calculation is applied to every value in the array.
</div>

Example:

- If every customer gets a 10 percent increase in spend estimate, we can multiply all values by `1.10`.
- NumPy does this directly without writing a manual loop.

<div style="background:#E9F8EF; border-left:6px solid #27AE60; padding:14px; border-radius:6px;">
<img src="../../../assets/icons/code.svg" width="22" style="vertical-align:middle; margin-right:6px;"><b>Code Lab</b><br>
Apply one calculation to all values in a NumPy array.
</div>

In [6]:
increased_spend = spend_array * 1.10

print("Original spend:", spend_array)
print("After 10 percent increase:", increased_spend.round(1))

Original spend: [1200  850 1450  700 2200]
After 10 percent increase: [1320.  935. 1595.  770. 2420.]

## <img src="../../../assets/icons/concept.svg" width="22" style="vertical-align:middle; margin-right:6px;"> Concept 6: Pandas Series

<div style="background:#EAF3FF; border-left:6px solid #2F80ED; padding:14px; border-radius:6px;">
<img src="../../../assets/icons/concept.svg" width="22" style="vertical-align:middle; margin-right:6px;"><b>Concept</b><br>
A Pandas Series is one labeled column of data.
</div>

### Simple memory line

- Series = one column
- DataFrame = full table

<div style="background:#E9F8EF; border-left:6px solid #27AE60; padding:14px; border-radius:6px;">
<img src="../../../assets/icons/code.svg" width="22" style="vertical-align:middle; margin-right:6px;"><b>Code Lab</b><br>
Create a Pandas Series for membership types.
</div>

In [7]:
import pandas as pd

membership_series = pd.Series(["Gold", "Silver", "Gold", "Bronze", "Silver"], name="membership")

membership_series

0      Gold
1    Silver
2      Gold
3    Bronze
4    Silver
Name: membership, dtype: object

## <img src="../../../assets/icons/concept.svg" width="22" style="vertical-align:middle; margin-right:6px;"> Concept 7: Pandas DataFrame

<div style="background:#EAF3FF; border-left:6px solid #2F80ED; padding:14px; border-radius:6px;">
<img src="../../../assets/icons/concept.svg" width="22" style="vertical-align:middle; margin-right:6px;"><b>Concept</b><br>
A DataFrame is a table made of rows and columns.
</div>

### In this example

- One row is one customer.
- Each column stores one detail about the customer.
- This small table is easy to inspect manually.

<div style="background:#E9F8EF; border-left:6px solid #27AE60; padding:14px; border-radius:6px;">
<img src="../../../assets/icons/code.svg" width="22" style="vertical-align:middle; margin-right:6px;"><b>Code Lab</b><br>
Create a customer purchase DataFrame.
</div>

In [8]:
customers = pd.DataFrame({
    "customer_id": [101, 102, 103, 104, 105, 106],
    "name": ["Asha", "Ravi", "Meera", "John", "Fatima", "Chen"],
    "city": ["Mumbai", "Delhi", "Chennai", "Mumbai", "Delhi", "Chennai"],
    "membership": ["Gold", "Silver", "Gold", "Bronze", "Silver", "Gold"],
    "monthly_spend": [1200, 850, 1450, 700, 2200, 1600],
    "visits_per_month": [4, 3, 5, 2, 6, 5],
})

customers

   customer_id    name     city membership  monthly_spend  visits_per_month
0          101    Asha   Mumbai       Gold           1200                 4
1          102    Ravi    Delhi     Silver            850                 3
2          103   Meera  Chennai       Gold           1450                 5
3          104    John   Mumbai     Bronze            700                 2
4          105  Fatima    Delhi     Silver           2200                 6
5          106    Chen  Chennai       Gold           1600                 5

## <img src="../../../assets/icons/concept.svg" width="22" style="vertical-align:middle; margin-right:6px;"> Concept 8: Selecting Columns

<div style="background:#EAF3FF; border-left:6px solid #2F80ED; padding:14px; border-radius:6px;">
<img src="../../../assets/icons/concept.svg" width="22" style="vertical-align:middle; margin-right:6px;"><b>Concept</b><br>
Selecting columns means choosing only the information we need from a table.
</div>

### Why this matters

- Real datasets can have many columns.
- We often inspect only a few columns at a time.
- This keeps analysis focused.

<div style="background:#E9F8EF; border-left:6px solid #27AE60; padding:14px; border-radius:6px;">
<img src="../../../assets/icons/code.svg" width="22" style="vertical-align:middle; margin-right:6px;"><b>Code Lab</b><br>
Select customer name, city, and monthly spend.
</div>

In [9]:
selected_columns = customers[["name", "city", "monthly_spend"]]

selected_columns

     name     city  monthly_spend
0    Asha   Mumbai           1200
1    Ravi    Delhi            850
2   Meera  Chennai           1450
3    John   Mumbai            700
4  Fatima    Delhi           2200
5    Chen  Chennai           1600

## <img src="../../../assets/icons/concept.svg" width="22" style="vertical-align:middle; margin-right:6px;"> Concept 9: Filtering Rows

<div style="background:#EAF3FF; border-left:6px solid #2F80ED; padding:14px; border-radius:6px;">
<img src="../../../assets/icons/concept.svg" width="22" style="vertical-align:middle; margin-right:6px;"><b>Concept</b><br>
Filtering keeps rows that match a condition.
</div>

### Example condition

Keep customers whose monthly spend is greater than `1000`.

<div style="background:#E9F8EF; border-left:6px solid #27AE60; padding:14px; border-radius:6px;">
<img src="../../../assets/icons/code.svg" width="22" style="vertical-align:middle; margin-right:6px;"><b>Code Lab</b><br>
Filter high-spending customers.
</div>

In [10]:
high_spend_customers = customers[customers["monthly_spend"] > 1000]

high_spend_customers

   customer_id    name     city membership  monthly_spend  visits_per_month
0          101    Asha   Mumbai       Gold           1200                 4
2          103   Meera  Chennai       Gold           1450                 5
4          105  Fatima    Delhi     Silver           2200                 6
5          106    Chen  Chennai       Gold           1600                 5

## <img src="../../../assets/icons/concept.svg" width="22" style="vertical-align:middle; margin-right:6px;"> Concept 10: Sorting Data

<div style="background:#EAF3FF; border-left:6px solid #2F80ED; padding:14px; border-radius:6px;">
<img src="../../../assets/icons/concept.svg" width="22" style="vertical-align:middle; margin-right:6px;"><b>Concept</b><br>
Sorting arranges rows based on a column.
</div>

### Why this matters

- Sorting helps find highest and lowest values quickly.
- It is useful before writing observations.

<div style="background:#E9F8EF; border-left:6px solid #27AE60; padding:14px; border-radius:6px;">
<img src="../../../assets/icons/code.svg" width="22" style="vertical-align:middle; margin-right:6px;"><b>Code Lab</b><br>
Sort customers by monthly spend from highest to lowest.
</div>

In [11]:
customers_sorted = customers.sort_values("monthly_spend", ascending=False)

customers_sorted

   customer_id    name     city membership  monthly_spend  visits_per_month
4          105  Fatima    Delhi     Silver           2200                 6
5          106    Chen  Chennai       Gold           1600                 5
2          103   Meera  Chennai       Gold           1450                 5
0          101    Asha   Mumbai       Gold           1200                 4
1          102    Ravi    Delhi     Silver            850                 3
3          104    John   Mumbai     Bronze            700                 2

## <img src="../../../assets/icons/concept.svg" width="22" style="vertical-align:middle; margin-right:6px;"> Concept 11: Adding a New Column

<div style="background:#EAF3FF; border-left:6px solid #2F80ED; padding:14px; border-radius:6px;">
<img src="../../../assets/icons/concept.svg" width="22" style="vertical-align:middle; margin-right:6px;"><b>Concept</b><br>
A new column can be created from existing columns.
</div>

### Example

If we know monthly spend and visits per month, we can calculate spend per visit.

<div style="background:#E9F8EF; border-left:6px solid #27AE60; padding:14px; border-radius:6px;">
<img src="../../../assets/icons/code.svg" width="22" style="vertical-align:middle; margin-right:6px;"><b>Code Lab</b><br>
Create a new column called `spend_per_visit`.
</div>

In [12]:
customers["spend_per_visit"] = customers["monthly_spend"] / customers["visits_per_month"]

customers

,customer_id,name,city,membership,monthly_spend,visits_per_month,spend_per_visit
0,101,Asha,Mumbai,Gold,1200,4,300.000000
1,102,Ravi,Delhi,Silver,850,3,283.333333
2,103,Meera,Chennai,Gold,1450,5,290.000000
3,104,John,Mumbai,Bronze,700,2,350.000000
4,105,Fatima,Delhi,Silver,2200,6,366.666667
5,106,Chen,Chennai,Gold,1600,5,320.000000

## <img src="../../../assets/icons/concept.svg" width="22" style="vertical-align:middle; margin-right:6px;"> Concept 12: Grouping and Summarizing

<div style="background:#EAF3FF; border-left:6px solid #2F80ED; padding:14px; border-radius:6px;">
<img src="../../../assets/icons/concept.svg" width="22" style="vertical-align:middle; margin-right:6px;"><b>Concept</b><br>
Grouping means splitting data into categories and calculating summaries for each category.
</div>

### Example question

What is the average monthly spend for each membership type?

<div style="background:#E9F8EF; border-left:6px solid #27AE60; padding:14px; border-radius:6px;">
<img src="../../../assets/icons/code.svg" width="22" style="vertical-align:middle; margin-right:6px;"><b>Code Lab</b><br>
Group customers by membership and calculate average monthly spend.
</div>

In [13]:
membership_summary = customers.groupby("membership")["monthly_spend"].mean().reset_index()

membership_summary

  membership  monthly_spend
0     Bronze     700.000000
1       Gold    1416.666667
2     Silver    1525.000000

## <img src="../../../assets/icons/recap.svg" width="22" style="vertical-align:middle; margin-right:6px;"> Concept Summary Table

<table style="margin-left:0; margin-right:auto; border-collapse:collapse; text-align:left;">
  <thead>
    <tr>
      <th style="text-align:left; padding:6px 12px;">Concept</th>
      <th style="text-align:left; padding:6px 12px;">Simple meaning</th>
      <th style="text-align:left; padding:6px 12px;">Example</th>
    </tr>
  </thead>
  <tbody>
    <tr><td style="text-align:left; padding:6px 12px;">Variable</td><td style="text-align:left; padding:6px 12px;">Named storage</td><td style="text-align:left; padding:6px 12px;"><code>monthly_spend = 1200</code></td></tr>
    <tr><td style="text-align:left; padding:6px 12px;">List</td><td style="text-align:left; padding:6px 12px;">Ordered collection</td><td style="text-align:left; padding:6px 12px;"><code>[1200, 850, 1450]</code></td></tr>
    <tr><td style="text-align:left; padding:6px 12px;">Dictionary</td><td style="text-align:left; padding:6px 12px;">Labeled values</td><td style="text-align:left; padding:6px 12px;"><code>{"city": "Mumbai"}</code></td></tr>
    <tr><td style="text-align:left; padding:6px 12px;">NumPy array</td><td style="text-align:left; padding:6px 12px;">Numeric collection</td><td style="text-align:left; padding:6px 12px;"><code>np.array([...])</code></td></tr>
    <tr><td style="text-align:left; padding:6px 12px;">Series</td><td style="text-align:left; padding:6px 12px;">One Pandas column</td><td style="text-align:left; padding:6px 12px;"><code>pd.Series(...)</code></td></tr>
    <tr><td style="text-align:left; padding:6px 12px;">DataFrame</td><td style="text-align:left; padding:6px 12px;">Pandas table</td><td style="text-align:left; padding:6px 12px;"><code>pd.DataFrame(...)</code></td></tr>
  </tbody>
</table>

## <img src="../../../assets/icons/caution.svg" width="22" style="vertical-align:middle; margin-right:6px;"> Common Mistakes to Avoid

<div style="background:#FFECEC; border-left:6px solid #EB5757; padding:14px; border-radius:6px;">
<b>Read this before practice.</b>
</div>

- Forgetting that Python positions start at `0`, not `1`.
- Using unclear variable names like `x` when a clearer name is possible.
- Confusing a Pandas Series with a DataFrame.
- Forgetting double brackets when selecting multiple DataFrame columns.
- Running cells out of order and then wondering why a variable is missing.

## <img src="../../../assets/icons/practice.svg" width="22" style="vertical-align:middle; margin-right:6px;"> Practice Task

Complete these tasks:

1. Add a new customer to the `customers` DataFrame.
2. Select only `name`, `membership`, and `visits_per_month`.
3. Filter customers from `Delhi`.
4. Sort customers by `visits_per_month` from highest to lowest.
5. Create a new column called `annual_spend` by multiplying `monthly_spend` by `12`.
6. Group by `city` and calculate average `monthly_spend`.

## <img src="../../../assets/icons/practice.svg" width="22" style="vertical-align:middle; margin-right:6px;"> Exit Ticket

Answer these before closing the notebook:

1. What is the difference between a list and a dictionary?
2. What is the difference between a Series and a DataFrame?
3. What does filtering do?
4. What does grouping do?
5. Why are clear column names important?

## <img src="../../../assets/icons/recap.svg" width="22" style="vertical-align:middle; margin-right:6px;"> Ready for the Next Notebook

You are ready for the next notebook if you can:

- Create a small DataFrame.
- Select columns from a DataFrame.
- Filter rows using a condition.
- Sort rows by a column.
- Add a calculated column.
- Group data and calculate a summary.